# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-24 17:37
from __future__ import unicode_literals

from django.db import migrations, models

PAIEMENT = {
  "EVEIL_1": 175,
  "ENFANT_1": 185,
  "ENFANT_2": 308,
  "ADO_1": 195,
  "ADO_2": 325,
  "ADULTE_1": 220,
  "ADULTE_2": 359
}

def compute_existing_totals(apps, _):
    Personne = apps.get_model("api", "Personne")
    for p in Personne.objects.all():
        categorie = p.categorie
        nbCours = len(p.cours.all())
        if nbCours > 0 and categorie is not None:
            p.somme_totale = PAIEMENT.get(categorie + "_" + str(nbCours), 0)
            p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170910_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='somme_totale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(compute_existing_totals)
    ]
