# Generated by Django 2.1.1 on 2018-09-16 20:57

from django.db import migrations, models
import django.db.models.deletion
from datetime import date


def add_period(apps, _):
    Personne = apps.get_model("api", "Personne")
    Periode = apps.get_model("api", "Periode")
    Inscription = apps.get_model("api", "Inscription")
    Cours = apps.get_model("api", "Cours")
    Paiement = apps.get_model("api", "Paiement")

    prev_period = Periode.objects.create(
        debut=date.fromisoformat("2017-09-01"),
        fin=date.fromisoformat("2018-06-30"))

    for c in Cours.objects.all():
        c.periode = prev_period
        c.save()

    for p in Personne.objects.all():
        if p.cours.count() == 0:
            continue

        inscription = Inscription.objects.create(
            droit_image=p.droit_image,
            photo=p.photo,
            fiche_adhesion=p.fiche_adhesion,
            certificat_medical=p.certificat_medical,
            somme_totale=p.somme_totale,
            periode=prev_period,
            inscrit=p)
        inscription.cours.set(p.cours.all())
        inscription.save()

        for paiement in Paiement.objects.filter(payeur=p):
            paiement.inscription = inscription


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_personne_somme_totale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droit_image', models.BooleanField(default=False)),
                ('photo', models.BooleanField(default=False)),
                ('fiche_adhesion', models.BooleanField(default=False)),
                ('certificat_medical', models.BooleanField(default=False)),
                ('somme_totale', models.IntegerField(blank=True, null=True)),
                ('cours', models.ManyToManyField(blank=True, related_name='inscriptions', to='api.Cours')),
                ('inscrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.Personne')),
            ],
            options={
                'verbose_name': "Dossier d'inscription",
                'verbose_name_plural': "Dossiers d'inscription",
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Periode',
                'verbose_name_plural': 'Periodes',
            },
        ),
        migrations.AddField(
            model_name='inscription',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Periode'),
        ),
        migrations.AddField(
            model_name='cours',
            name='periode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Periode'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='inscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.Inscription'),
        ),
        migrations.RunPython(add_period),
    ]
